### ISSUE TITLE
Itemprop "Position" Number Incorrect

### ISSUE THREAD

**Issue by lchambers** [orige/yii2-schema-breadcrumbs#1]
When a breadcrumb is output the number within <meta itemprop="position" content="{number}" /> is incorrect.

Looking at the code there is the following on line 82:

`$meta_content = count($this->totalLinks) + 1;`

Changing it to the following gives the correct position count:

`$meta_content = $this->totalLinks + 1;`

Great plugin by the way - it's saved me some time writing my own!

**Comment by orige** [comment]
@lchambers Thanks for your help and feedback bud!
